# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_donor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganRequired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('heart', 'Heart'), ('lungs', 'Lungs'), ('kidney', 'Kidney'), ('liver', 'Liver'), ('blood', 'Blood')], max_length=100)),
                ('blood_group', models.CharField(choices=[('ave', 'A+ve'), ('a-ve', 'A-ve'), ('bve', 'B+ve'), ('b-ve', 'B-ve'), ('ove', 'O+ve'), ('o-ve', 'O-ve'), ('abve', 'AB+ve'), ('ab-ve', 'AB-ve')], max_length=20)),
                ('organ_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_patient', to='website.Donor')),
            ],
        ),
    ]
